-- ============================================================================
-- Phase 0: organizations, users, org_members + multi-tenant RLS foundation.
-- RLS is enabled in this same migration, not a follow-up — see CLAUDE.md.
-- ============================================================================

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "org_role" AS ENUM ('owner', 'admin', 'agent', 'cp_admin', 'cp_agent');

-- CreateTable
CREATE TABLE "organizations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Mirrors auth.users. id is populated by the handle_new_user trigger below,
-- always equal to the corresponding auth.users.id — enforced by the FK at
-- the bottom of this file.
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "full_name" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "org_members" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" "org_role" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "org_members_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "organizations_slug_key" ON "organizations"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "org_members_org_id_user_id_key" ON "org_members"("org_id", "user_id");

-- AddForeignKey
ALTER TABLE "org_members" ADD CONSTRAINT "org_members_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "org_members" ADD CONSTRAINT "org_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey — ties public.users.id to the real Supabase Auth identity.
-- Not generated by Prisma (auth.users lives outside its schema).
ALTER TABLE "users" ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;


-- ============================================================================
-- Signup trigger: mirror new auth.users rows into public.users.
-- Standard Supabase pattern. security definer + fixed search_path so the
-- function can write into public.users despite RLS, without being hijackable
-- via a mutated search_path.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================================
-- RLS helper functions — live in their own schema so they aren't exposed as
-- PostgREST RPC endpoints the way a public-schema function would be.
--
-- security definer + owned by the migration role (postgres) means these
-- bypass RLS internally on the tables they query — required, otherwise a
-- policy that calls one of these would recurse into the very policy it's
-- trying to evaluate. This is the standard, documented Supabase pattern for
-- RLS helper functions.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS app;

-- Is the calling user a member of check_org_id, in any role?
CREATE OR REPLACE FUNCTION app.is_org_member(check_org_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.org_members
    WHERE org_id = check_org_id
      AND user_id = auth.uid()
  );
$$;

-- Is the calling user an owner or admin of check_org_id?
CREATE OR REPLACE FUNCTION app.is_org_admin(check_org_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.org_members
    WHERE org_id = check_org_id
      AND user_id = auth.uid()
      AND role IN ('owner', 'admin')
  );
$$;

-- Does the calling user share at least one org with target_user_id?
CREATE OR REPLACE FUNCTION app.shares_org_with(target_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.org_members mine
    JOIN public.org_members theirs ON theirs.org_id = mine.org_id
    WHERE mine.user_id = auth.uid()
      AND theirs.user_id = target_user_id
  );
$$;

-- Granted to anon as well as authenticated: our policies apply to every
-- role (no `TO` clause), including anonymous requests, and rely on
-- auth.uid() resolving to NULL for anon rather than a missing grant to
-- turn that case into a permission error instead of zero rows.
GRANT USAGE ON SCHEMA app TO authenticated, anon;
GRANT EXECUTE ON FUNCTION app.is_org_member(UUID) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION app.is_org_admin(UUID) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION app.shares_org_with(UUID) TO authenticated, anon;


-- ============================================================================
-- Row Level Security — the actual tenancy boundary. A query without the
-- correct org context matches no policy and returns zero rows, never an
-- error and never another tenant's data.
-- ============================================================================

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_members ENABLE ROW LEVEL SECURITY;

-- organizations: visible to members; editable by owner/admin. No client-side
-- INSERT/DELETE policy — org creation and deletion are Phase 1+ concerns
-- (onboarding flow), handled server-side via the service role in the
-- meantime, not exposed to RLS-governed client queries yet.
CREATE POLICY "org members can view their org"
  ON public.organizations
  FOR SELECT
  USING (app.is_org_member(id));

CREATE POLICY "org owners and admins can update their org"
  ON public.organizations
  FOR UPDATE
  USING (app.is_org_admin(id));

-- users: a user always sees their own row, plus teammates who share an org
-- with them. Row creation happens only via the handle_new_user trigger
-- (security definer, bypasses RLS) — no INSERT policy needed.
CREATE POLICY "users can view self and org teammates"
  ON public.users
  FOR SELECT
  USING (id = auth.uid() OR app.shares_org_with(id));

CREATE POLICY "users can update self"
  ON public.users
  FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- org_members: visible to fellow members of the same org; membership is
-- managed by that org's owners/admins.
CREATE POLICY "org members can view memberships in their org"
  ON public.org_members
  FOR SELECT
  USING (app.is_org_member(org_id));

CREATE POLICY "org owners and admins can add members"
  ON public.org_members
  FOR INSERT
  WITH CHECK (app.is_org_admin(org_id));

CREATE POLICY "org owners and admins can update members"
  ON public.org_members
  FOR UPDATE
  USING (app.is_org_admin(org_id));

CREATE POLICY "org owners and admins can remove members"
  ON public.org_members
  FOR DELETE
  USING (app.is_org_admin(org_id));
