/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdAccountsRouteImport } from './routes/ad-accounts'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as DataRouteImport } from './routes/data'
import { Route as GlobalConfigRouteImport } from './routes/global-config'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAccountsRoute = AdAccountsRouteImport.update({
  id: '/ad-accounts',
  path: '/ad-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalConfigRoute = GlobalConfigRouteImport.update({
  id: '/global-config',
  path: '/global-config',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ad-accounts': typeof AdAccountsRoute
  '/attendance': typeof AttendanceRoute
  '/data': typeof DataRoute
  '/global-config': typeof GlobalConfigRoute
  '/invoice': typeof InvoiceRoute
  '/leads': typeof LeadsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ad-accounts': typeof AdAccountsRoute
  '/attendance': typeof AttendanceRoute
  '/data': typeof DataRoute
  '/global-config': typeof GlobalConfigRoute
  '/invoice': typeof InvoiceRoute
  '/leads': typeof LeadsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ad-accounts': typeof AdAccountsRoute
  '/attendance': typeof AttendanceRoute
  '/data': typeof DataRoute
  '/global-config': typeof GlobalConfigRoute
  '/invoice': typeof InvoiceRoute
  '/leads': typeof LeadsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ad-accounts'
    | '/attendance'
    | '/data'
    | '/global-config'
    | '/invoice'
    | '/leads'
    | '/profile'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/tasks'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ad-accounts'
    | '/attendance'
    | '/data'
    | '/global-config'
    | '/invoice'
    | '/leads'
    | '/profile'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/tasks'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/ad-accounts'
    | '/attendance'
    | '/data'
    | '/global-config'
    | '/invoice'
    | '/leads'
    | '/profile'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/tasks'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdAccountsRoute: typeof AdAccountsRoute
  AttendanceRoute: typeof AttendanceRoute
  DataRoute: typeof DataRoute
  GlobalConfigRoute: typeof GlobalConfigRoute
  InvoiceRoute: typeof InvoiceRoute
  LeadsRoute: typeof LeadsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  PropertiesRoute: typeof PropertiesRoute
  ReportsRoute: typeof ReportsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts': {
      id: '/ad-accounts'
      path: '/ad-accounts'
      fullPath: '/ad-accounts'
      preLoaderRoute: typeof AdAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-config': {
      id: '/global-config'
      path: '/global-config'
      fullPath: '/global-config'
      preLoaderRoute: typeof GlobalConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdAccountsRoute: AdAccountsRoute,
  AttendanceRoute: AttendanceRoute,
  DataRoute: DataRoute,
  GlobalConfigRoute: GlobalConfigRoute,
  InvoiceRoute: InvoiceRoute,
  LeadsRoute: LeadsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  PropertiesRoute: PropertiesRoute,
  ReportsRoute: ReportsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
